excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://michaelwheeler.github.io
title: Awesome
email: 
author: Michael Wheeler
description: My awesome new site
paginate: 3
google_analytics: 